CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(50)                             NOT NULL,
    email VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS quotes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(500)                            NOT NULL,
    created     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    author_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_quote PRIMARY KEY (id),
    CONSTRAINT fk_quotes_to_users FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS votes
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    user_id  BIGINT                                  NOT NULL,
    quote_id BIGINT                                  NOT NULL,
    reaction VARCHAR(8)                              NOT NULL,
    CONSTRAINT pk_vote PRIMARY KEY (id),
    CONSTRAINT fk_votes_to_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_votes_to_quotes FOREIGN KEY (quote_id) REFERENCES quotes (id) ON DELETE CASCADE,
    UNIQUE (user_id, quote_id)
);